/**
 * This module provides utility functions for working with functions, including caching and memoization.
 *
 * @module
 * @importTarget ./function
 */

import type { UnknownArray } from 'type-fest';

import type {
  AnyFunction,
  Predicate,
  UnknownFunction,
} from '@budsbox/lib-types';

import {
  type NormalizedOptionalRest,
  assertArray,
  assertEvery,
  assertFunction,
  isFunction,
  isInteger,
  isPositive,
} from '#guards';
import { normalizeOptionalRest as _normalizeOptionalRest } from '#guards/assert';

/**
 * A function that does nothing.
 */
export const noop = (): void => {};

/**
 * A function that returns its argument.
 *
 * @param value - The value to return.
 * @returns The input value.
 */
export const pass = <T>(value: T): T => value;

type CacheableFn<TFn extends AnyFunction> =
  Parameters<TFn> extends [unknown, ...UnknownArray] ? TFn : never;

type DefaultCacheKey<TFn extends AnyFunction> =
  Parameters<TFn> extends [infer TArg0, ...UnknownArray] ? TArg0 : never;

type CachedFn<TFn extends AnyFunction, TKey = DefaultCacheKey<TFn>> =
  TFn extends (...args: infer TArgs) => infer TReturn ?
    (cacheMap: Map<TKey, TReturn>, ...args: TArgs) => TReturn
  : never;

/**
 * Creates a cached version of a given function.
 * The returned function stores the results of previous calls in a provided cache map
 * and returns the cached result when called with the same arguments,
 * reducing redundant calculations or operations.
 *
 * @param fn - The function to be cached.
 * @returns A new function that accepts the cache map as the first argument and the original function's arguments as the rest.
 * @remarks A provided function has to accept at least one argument, or it fails typechecking.
 * @typeParam TFn - The type of function to be cache. It extends `AnyFunction` type.
 */
export function createCachedFn<TFn extends AnyFunction>(
  fn: CacheableFn<TFn>,
): CachedFn<TFn>;

/**
 * Creates a cached version of a given function.
 * The returned function stores the results of previous calls in a provided cache map
 * and returns the cached result when called with the same arguments,
 * reducing redundant calculations or operations. The caching behavior is
 * determined by a key generation function (`keyFn`) which computes a unique
 * key for each set of arguments. If the same key is generated for later
 * calls, the cached result is returned instead of invoking the original function.
 *
 * @param fn - The function to be cached.
 * @param keyFn - A function that generates a unique key based on the arguments passed to `fn`.
 * @returns A new function that accepts the cache map as the first argument and the original function's arguments as the rest.
 * @remarks A provided function has to accept at least one argument, or it fails typechecking.
 * @typeParam TFn - The type of function to be cache. It extends the ` AnyFunction ` type.
 * @typeParam TKey - The type of key generated by the key function.
 */
export function createCachedFn<TFn extends AnyFunction, TKey>(
  fn: CacheableFn<TFn>,
  keyFn: (...args: Parameters<TFn>) => TKey,
): CachedFn<TFn, TKey>;
export function createCachedFn(
  fn: UnknownFunction,
  keyFn: UnknownFunction = pass,
): AnyFunction {
  assertFunction(fn, 'fn');
  assertFunction(keyFn, 'keyFn');
  return (map: Map<unknown, unknown>, ...args: UnknownArray) => {
    const key = keyFn(...args);
    if (map.has(key)) return map.get(key);

    const result = fn(...args);
    map.set(key, result);

    return result;
  };
}

/**
 * Normalizes a sequence of optional rest arguments by matching them against a series of type predicates.
 *
 * This function takes an array of arguments and attempts to match each argument against the corresponding
 * predicate in the sequence. Arguments that match their predicates are placed at their respective positions
 * in the output array, while unmatched positions are filled with `undefined`. This enables flexible function
 * signatures where arguments can be provided with gaps as long as they're in the right order.
 *
 * The function validates that:
 * - No more arguments are provided than there are predicates
 * - Each argument matches its corresponding predicate in sequence
 * - Any remaining arguments after a successful match also satisfy the subsequent predicates
 *
 * @param predicateSequence - An ordered array of type predicates that define the expected types for each position.
 * @param args - The actual arguments to normalize against the predicate sequence.
 * @param restShift - An optional offset added to argument indices in error messages, useful when these
 *                   arguments are part of a larger parameter list. Defaults to 0.
 * @returns A tuple where each element is either the matched argument value or `undefined` if no match was found
 *         at that position. The length matches the predicate sequence length.
 * @throws {@link !TypeError} If more arguments are provided than predicates in the sequence.
 * @throws {@link !TypeError} If an argument doesn't match any of the remaining predicates in the sequence.
 * @typeParam TPredicateSequence - a tuple of predicate types.
 * @remarks For this function to work, a predicate sequence has to be tuple. Use `as const` to convert array to tuple.
 * @example
 * ```typescript
 * normalizeOptionalRest([isString, isBoolean, isNumber], ['foo'])
 * // Returns: ['foo', undefined, undefined]
 *
 * normalizeOptionalRest([isString, isBoolean, isNumber], [true])
 * // Returns: [undefined, true, undefined]
 *
 * normalizeOptionalRest([isString, isBoolean, isNumber], ['foo', true, 1])
 * // Returns: ['foo', true, 1]
 *
 * normalizeOptionalRest([isString, isBoolean, isNumber] as const, ['foo', 1])
 * // Returns: ['foo', undefined, 1]
 *
 * // Using restShift for better error messages in nested contexts
 * normalizeOptionalRest([isString, isBoolean] as const, ['foo', 'bar'], 2)
 * // Throws: TypeError with message referencing rest[3] instead of rest[1]
 *
 * // Trailing undefined values are ignored
 * normalizeOptionalRest([isString, isBoolean, isNumber] as const, ['foo', true, undefined])
 * // Returns: ['foo', true, undefined]
 * ```
 */
export function normalizeOptionalRest<
  TPredicateSequence extends ReadonlyArray<Predicate<unknown>>,
>(
  predicateSequence: TPredicateSequence,
  args: readonly unknown[],
  restShift?: number,
): NormalizedOptionalRest<TPredicateSequence>;
export function normalizeOptionalRest(
  predicateSequence: ReadonlyArray<Predicate<unknown>>,
  args: readonly unknown[],
  restShift: number = 0,
): unknown[] {
  assertArray(predicateSequence, isFunction);
  assertArray(args);
  assertEvery(restShift, 'restShift', isInteger, isPositive);

  return _normalizeOptionalRest(predicateSequence, args, restShift);
}
