yarnPath: .yarn/releases/yarn-4.0.2.cjs
nodeLinker: pnp
enableGlobalCache: false
injectEnvironmentFiles:
  - .env?
  - .env.example?
changesetBaseRefs:
  - trunk
  - origin/trunk
  - upstream/trunk
  - main
  - origin/main
  - upstream/main
  - master
  - origin/master
  - upstream/master
