changesetBaseRefs:
  - trunk
  - origin/trunk
  - upstream/trunk
  - main
  - origin/main
  - upstream/main
  - master
  - origin/master
  - upstream/master

enableGlobalCache: false

injectEnvironmentFiles:
  - packages/*/.env?
  - .env?
  - .env.example?

nodeLinker: pnp

yarnPath: .yarn/releases/yarn-4.1.0.cjs
