changesetBaseRefs:
  - trunk
  - origin/trunk
  - upstream/trunk
  - main
  - origin/main
  - upstream/main
  - master
  - origin/master
  - upstream/master

enableConstraintsChecks: true

enableGlobalCache: false

initScope: budsbox

injectEnvironmentFiles:
  - .env.default
  - .env?

nodeLinker: pnp

npmPublishAccess: public

npmScopes:
  budsbox:
    npmAuthToken: "${NPM_SCOPE_ACCESS_TOKEN}"

preferInteractive: true

preferReuse: true

yarnPath: .yarn/releases/yarn-4.5.3.cjs
