/**
 * @module @budsbox/parse-mime
 * @file Main entry point for the MIME type parser.
 *
 * This module provides functions for parsing and serializing MIME types according to
 * the WHATWG MIME Sniffing Standard and related RFCs. The parser is generated using Peggy
 * and supports multiple parsing strategies, parameter handling, and serialization.
 */

import type {
  DefaultStartRule,
  MultiParameterOption,
  ParseOptions,
  RuleResult,
  SerializableMimeTypeRecord,
  SerializableParameters,
  StartRuleNames,
} from '#types';

import {
  assertArray,
  assertOptionalProp,
  assertProp,
  assertSome,
  assertString,
  isArray,
  isIterable,
  isObject,
  isString,
  isUndef,
  somePredicate,
} from '@budsbox/lib-es/guards';

import * as Parser from '#parser';

// Type exports
export type * from '#types';

/**
 * Syntax error thrown by the parser when input doesn't match the grammar.
 * This error is generated by Peggy and includes detailed location information
 * about where parsing failed.
 *
 */
// it's reexported as a const to add jsdoc to it
export const SyntaxError = Parser.SyntaxError;

/**
 * Represents the default starting rule for the parser.
 */
export const defaultStartRule: DefaultStartRule = 'mimeType';

/**
 * Parses a MIME type string or component using the Peggy-generated parser.
 *
 * This is the primary parsing function that can parse complete MIME types or individual
 * components depending on the specified start rule. It supports various parsing strategies
 * for handling edge cases like duplicate parameters and whitespace.
 *
 * @param input - The string to parse (e.g., "text/html; charset=utf-8")
 * @param options - Optional parsing configuration
 * @param options.startRule - Which grammar rule to start parsing from. Defaults to `'mimeType'`.
 * @param options.multiParameter - How to handle duplicate parameters ('keep-first', 'keep-last', or 'list'). Defaults to `'keep-first'`.
 * @param options.sniff - Whether to use lenient parsing mode. Defaults to `false`.
 * @param options.trim - Whether to trim whitespace before parsing. Defaults to `options.sniff === true`.
 * @param options.restrictNames - Whether to enforce strict naming conventions. Defaults to `!options.sniff`.
 * @param options.tracer - Optional parser tracer for debugging.
 * @param options.grammarSource - Optional source information for error messages.
 * @returns Parsed result based on the start rule. For 'mimeType' (default), returns a
 * complete parsed MIME type with essence and parameters. Other rules return specific components.
 * @throws {SyntaxError} When the input doesn't match the expected grammar
 * @typeParam TRule - The grammar start rule to use for parsing. Determines which component
 * of a MIME type to parse (e.g., 'mimeType', 'essence', 'parameter'). Defaults to parsing
 * complete MIME types.
 * @typeParam TMultiParameter - Strategy for handling duplicate parameter names. Defaults to
 * 'keep-first', which retains only the first occurrence of duplicate parameters.
 * @see {@link sniff} — for a convenience wrapper that automatically enables sniff mode.
 * @see {@link RuleResult} — for the map of a parsing result for every `options.startRule` value.
 * @example
 * ```typescript
 * // Parse a complete MIME type
 * const result = parse('text/html; charset=utf-8');
 * // result.type === 'text'
 * // result.subtype === 'html'
 * // result.parameters.get('charset') === 'utf-8'
 * ```
 * @example
 * ```typescript
 * // Parse just the essence (type/subtype without parameters)
 * const essence = parse('application/json', { startRule: 'essence' });
 * // essence.type === 'application'
 * // essence.subtype === 'json'
 * ```
 */
export const parse = Parser.parse as <
  TRule extends StartRuleNames = DefaultStartRule,
  TMultiParameter extends MultiParameterOption = 'keep-first',
>(
  input: string,
  options?: ParseOptions<TRule, TMultiParameter>,
) => RuleResult<TMultiParameter>[TRule];

/**
 * Parses a MIME type string in lenient "sniffing" mode.
 *
 * This is a convenience wrapper around {@link parse} that automatically enables
 * the `sniff` option. Sniffing mode attempts to extract valid MIME type information
 * even from malformed input, following the WHATWG MIME Sniffing Standard algorithm.
 * This is useful when parsing potentially non-standard MIME types from user input
 * or legacy systems.
 *
 * @param input - The string to parse
 * @param options - Optional parsing configuration (excluding 'sniff' which is always true)
 * @returns Parsed result based on the start rule, same as {@link parse}
 * @throws {SyntaxError} When the input cannot be parsed even in lenient mode
 * @typeParam TRule - The grammar start rule to use for parsing
 * @typeParam TMultiParameter - Strategy for handling duplicate parameter names
 */
export const sniff = <
  TRule extends StartRuleNames = DefaultStartRule,
  TMultiParameter extends MultiParameterOption = 'keep-first',
>(
  input: string,
  options?: Readonly<Omit<ParseOptions<TRule, TMultiParameter>, 'sniff'> & {}>,
): RuleResult<TMultiParameter>[TRule] => {
  assertSome(options, 'options', isObject, isUndef);

  return parse(input, { ...options, sniff: true });
};

/**
 * Type alias for the {@link parse} function signature.
 * Useful for type annotations when passing the parse function as a parameter.
 *
 */
export type ParseFunction = typeof parse;

// eslint-disable-next-line jsdoc/require-throws,jsdoc/lines-before-block
/**
 * Checks whether a string is a valid HTTP token, according both to IETF and WHATWG standards.
 *
 * @internal
 * @param value - The string to validate
 * @returns `true` if the value is a valid HTTP token, `false` otherwise
 * @see @{link https://mimesniff.spec.whatwg.org/#http-token-code-point MIME Sniffing Standard: HTTP Token Code Point}
 * — for the description of the HTTP Token used in WHATWG MIME Sniffing Standard.
 * @see @{link https://datatracker.ietf.org/doc/html/rfc9110#name-tokens RFC 9110: Tokens}
 * — for the syntax of HTTP tokens as defined by IETF standards.
 */
const isHttpToken = (value: string): boolean => {
  try {
    return value === parse(value, { startRule: 'httpToken' });
  } catch (err) {
    if (err instanceof SyntaxError) {
      return false;
    }

    throw err;
  }
};

/**
 * Serializes MIME type parameters into a string format suitable for inclusion in a MIME type.
 *
 * Converts a collection of parameter name-value pairs
 * or record, where key represents a parameter name and value is a parameter value
 * into the standard MIME type parameter syntax: `;name=value`.
 * Values are quoted if they are not valid HTTP tokens.
 * Handles arrays of values by expanding them into multiple parameters
 * with the same name.
 *
 * @param parameters - An iterable of parameter name-value pairs to serialize. Values can be
 * single strings or arrays of strings (for parameters that appear multiple times).
 * @returns A string containing serialized parameters in the format `;name1=value1;name2=value2`.
 * Returns an empty string if no parameters are provided.
 * @example
 * ```typescript
 * const params = new Map([
 *   ['charset', 'utf-8'],
 *   ['boundary', '----boundary']
 * ]);
 * const result = serializeParameters(params);
 * // result === ';charset=utf-8;boundary=----boundary'
 * ```
 * @example
 * ```typescript
 * // With special characters requiring quoting
 * const params = new Map([['filename', 'my file.txt']]);
 * const result = serializeParameters(params);
 * // result === ';filename="my file.txt"'
 * ```
 * @example
 * ```typescript
 * // With array values (multiple occurrences)
 * const params = [['foo', ['bar', 'baz']]];
 * const result = serializeParameters(params);
 * // result === ';foo=bar;foo=baz'
 * ```
 */
export const serializeParameters = (
  parameters: SerializableParameters<true>,
): string => {
  if (isUndef(parameters)) return '';
  assertSome(parameters, 'parameters', isObject, isIterable);
  const queue = [
    ...(isIterable(parameters) ? parameters : Object.entries(parameters)),
  ];
  const result: string[] = [];
  while (queue.length) {
    const parameter = queue.shift();
    assertArray(parameter, 'parameter');

    const [name, value] = parameter;
    assertString(name, 'parameter_name');
    if (isArray(value)) {
      assertArray(value, isString, 'parameter_value');
      queue.unshift(...value.map((v): [string, string] => [name, v]));
    } else {
      assertString(value, 'parameter_value');
      result.push(
        `;${name}=${
          isHttpToken(value) ? value : (
            `"${value.replace(/["\\]/g, (s) => `\\${s}`)}"`
          )
        }`,
      );
    }
  }

  return result.join('');
};

/**
 * Serializes a MIME type object into its string representation based on the MIME Sniffing Standard format.
 * It differs from the MIME Sniffing Standard algorithm in that it allows multiple parameters with the same name.
 * This is the inverse operation of parsing
 * and is useful for normalizing MIME types or constructing them programmatically.
 *
 * @param record - The "MIME type"-like record to serialize.
 * @returns A string representation of the MIME type in the format "type/subtype;param1=value1;param2=value2"
 * @see {@link parse} — for the inverse operation.
 * @see {@link SerializableMimeTypeRecord} — for the structure of the input object.
 * @see {@link https://mimesniff.spec.whatwg.org/#serializing-a-mime-type MIME Sniffing Standard: Serializing a MIME Type}
 * — for the full specification of the serialization algorithm.
 * @example
 * ```typescript
 * // Normalizing a MIME type
 * const parsed = parse('text/html; CHARSET=UTF-8');
 * const serialized = serializeMimeType(parsed);
 * // serialized === 'text/html;charset=utf-8'
 * ```
 * @example
 * ```typescript
 * // Constructing a MIME type programmatically
 * const mimeType: MimeTypeParsed = {
 *   type: 'application',
 *   subtype: 'json',
 *   parameters: [[['charset', 'utf-8']]]
 * };
 * const result = serializeMimeType(mimeType);
 * // result === 'application/json;charset=utf-8'
 * ```
 */
export const serializeMimeType = (
  record: SerializableMimeTypeRecord<true>,
): string => {
  assertProp(record, 'type', isString, 'record');
  assertProp(record, 'subtype', isString, 'record');
  assertOptionalProp(
    record,
    'parameters',
    somePredicate(isObject, isIterable, isUndef),
    'record',
  );

  const { type, subtype, parameters = [] } = record;

  return `${type}/${subtype}${serializeParameters(parameters)}`;
};
