name: Pull Request

on:
  pull_request:
    branches: [trunk]

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      YARN_GLOBAL_FOLDER: .yarn/global
      COREPACK_TAR_FILE: corepack.tgz

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Corepack
        run: corepack enable

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          check-latest: true
          cache: yarn
          package-manager-cache: true
          cache-dependency-path: yarn.lock

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Setup monorepo
        run: yarn run setup

      - name: Build Typings
        run: yarn workspaces foreach --since --parallel --topological run check:typings

      - name: Lint
        run: yarn workspaces foreach --since --parallel run check:lint

      - name: Test
        run: yarn workspaces foreach --since --parallel --topological run check:test
